development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: writing_app_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: writing_app_test
  pool: 5

production:
  adapter: postgresql
  host: localhost
  database: DATABASE_URL
  pool: 5